# Generated by Django 3.2.13 on 2022-05-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
